NAME : 'deeplabv3plus_bcos_sbert_des'
WANDB_LOG : True
MAX_EPOCHS : 60
FREEZE_ENCODER :  True
MODEL_TYPE : 'deeplabv3plus_contrastive'
MODEL_FROM_FILE : 'deeplabv3plus_base_best/model_last.pth'

FLAIR :
  SPLIT : '/base'  # either dev, or base
  TRAIN_PATCH_SIZE : 512
  TEST_PATCH_SIZE  : 512

train : 
  batch_size : 8
  optimizer_type : 'adam'
  scheduler_type : 'stepLR'
  lr : 1e-4
  contrastive : [{
    'embedding_path':'data/flair_labels/flair_descrip_sentenceBERT.pt',
    'temperature':1.5,
    'bcos_value':1.5,
    'embedding_size':768,
    'ignore_index':0,
    'augmented_path' :'',
    'use_augmentation':False,
    'nb_pos_vectors':0,
    'nb_neg_vectors':0,
                }]
